<a href="https://colab.research.google.com/github/Prasetya36/Machine-Leraning/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
!pip install -U -q pyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth= GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive= GoogleDrive(gauth)

In [ ]:
import pandas as pd
from google.colab.files import download
link = 'https://drive.google.com/open?id=1dIuZaS7jIHt6I8Gha60f-EJNIpFZceK2'
fluff, id = link.split('=')
print (id)
downloaded = drive.CreateFile({'id':id})
downloaded.GetContentFile('Persentase Perokok RI.csv')
dataset = pd.read_csv('Persentase Perokok RI.csv')

dataset.describe()

1dIuZaS7jIHt6I8Gha60f-EJNIpFZceK2

            2015       2016
count  34.000000  34.000000
mean   29.477647  28.352647
std     2.967069   2.931938
min    22.960000  21.620000
25%    27.555000  26.240000
50%    29.295000  28.270000
75%    31.502500  30.500000
max    34.120000  33.390000

In [ ]:
dataset.describe()

            2015       2016
count  34.000000  34.000000
mean   29.477647  28.352647
std     2.967069   2.931938
min    22.960000  21.620000
25%    27.555000  26.240000
50%    29.295000  28.270000
75%    31.502500  30.500000
max    34.120000  33.390000

In [ ]:
url = 'https://raw.githubusercontent.com/Prasetya36/Machine-Leraning/main/Persentase%20Perokok%20RI.csv'
dataset = pd.read_csv(url)
dataset.describe()

            2015       2016
count  34.000000  34.000000
mean   29.477647  28.352647
std     2.967069   2.931938
min    22.960000  21.620000
25%    27.555000  26.240000
50%    29.295000  28.270000
75%    31.502500  30.500000
max    34.120000  33.390000